
plane_pose_prefix   = 'planePose_'
world_gaze_prefix   = 'planeGaze_'
coding_file         = 'coding.tsv'
target_sync_prefix  = 'et_sync_target_'
VOR_sync_file       = 'VOR_sync.tsv'
gaze_offset_prefix  = 'gazeOffset_'
validation_prefix   = 'validate_'
mapped_gaze_video   = 'mappedGaze.mp4'
gaze_export_name    = 'planeGaze'